### ISSUE TITLE
using protobuild with multiple generator

### ISSUE THREAD

**Issue by Tommy-42** [containerd/protobuild#15]
Hello, 

I was wondering if protobuild could actually be able to be used with more than 1 generator ?

I can't use both `go_out` and `grpc-gateway_out` that I normaly use with `protoc` command line.
I have to do 2 `.toml` right ? 

I can't find anything on this topic.

Should it be supported ? 
Is it on a TODO ? 

Best regards,
Thanks for the awesome job tho !

**Comment by Tommy-42** [comment]
I have think about it.

Could we think about something like this : 

```toml
[[generator]]
  name = "gotemplate"

  [generator.options]
    debug = true
    template_dir = "."

[[generator]]
  name = "gogo"

  [generator.options]
    debug = true

  [generator.plugins]
    ["grpc", "blabla"]
```

**Comment by Tommy-42** [comment]
Hey 

I have forked an done something that might interest you, could you have a look and tell me if it can work for you ?  ( that should resolve #15 and #17 )

What I need to change, etc before pushing a PR ?

https://github.com/Tommy-42/protobuild

Thanks

**Comment by stevvooe** [comment]
Can you do this with overrides?

**Comment by stevvooe** [comment]
Is your proposal backwards compatible?

**Comment by stevvooe** [comment]
@Tommy-42 I guess send a pull request. Make sure there are examples of how the output gets generated, along with intermediary commands.

**Comment by kzys** [comment]
This could be addressed for supporting Google's latest Go code generator. It doesn't support gRPC plugin anymore.
