### ISSUE TITLE
Should the `overrides` prefixes be matching on filesystem case, or Go package name?

### ISSUE THREAD

**Issue by TBBle** [containerd/protobuild#47]
While trying to regenerate protobuf in hcsshim, I hit a surprising behaviour.

I was running this on Windows, and
```
protobuild github.com/Microsoft/hcsshim/internal/shimdiag
```
was not honouring the existing override in [Protobuf.toml](https://github.com/Microsoft/hcsshim/blob/1f8211a77a20be7a196e31f49d007ccc61dd0981/Protobuild.toml):

```
[[overrides]]
prefixes = ["github.com/Microsoft/hcsshim/internal/shimdiag"]
plugins = ["ttrpc"]
```

After much poking about, I found this works:
```
[[overrides]]
prefixes = [
  "github.com/Microsoft/hcsshim/internal/shimdiag",
  "github.com\\Microsoft\\hcsshim\\internal\\shimdiag",
]
plugins = ["ttrpc"]
```

Is this expected behaviour? I had expected (from my very limited exposure to this tool) that all these paths were in "Go package path" format, rather than being filesystem paths.

I only worked out what was going on when I noticed that the [prefix being looked up is defined with `filepath.Rel`](https://github.com/containerd/protobuild/blob/6b023c693abe4cd44e59ada8bdf496eb2572d9a6/main.go#L178-L192), and perhaps `filepath.ToSlash` should be used on the result before further processing? Or perhaps that would also be surprising for packages defined on the filesystem. (I don't know if Go enforces `/`-separators in that case or not.)

This is with protobuild 6b023c693abe4cd44e59ada8bdf496eb2572d9a6, rather than 0.1.0, due to #46.

**Comment by stevvooe** [comment]
This is not expected. It should handle the paths identically on both systems.

@kzys Can you have a look at this?

**Comment by kzys** [comment]
Sure.

**Comment by kzys** [comment]
> I only worked out what was going on when I noticed that the [prefix being looked up is defined with filepath.Rel](https://github.com/containerd/protobuild/blob/6b023c693abe4cd44e59ada8bdf496eb2572d9a6/main.go#L178-L192), and perhaps filepath.ToSlash should be used on the result before further processing?

@TBBle is right. Protobuild is assuming that what Go returns as filepaths are compatible with Go's import paths, which is not true on Windows.
